### ISSUE TITLE
Remove airscan dll.conf changes

### ISSUE THREAD

**Issue by hadess** [flathub/work.openpaper.Paperwork#12]
This line can be removed:
```
        "echo airscan >> /app/etc/sane.d/dll.conf"
```

sane-airscan already installs a file in the `dll.d` directory, see https://github.com/alexpevzner/sane-airscan/blob/master/Makefile#L121-L124

**Comment by jflesch** [comment]
Except I do not install scane-airscan in the Flatpak container at all. It looks like an oversight on my part.

**Comment by jflesch** [comment]
Fixed in 638306937662ea6b4fca950484abaf66d29aae15
