### ISSUE TITLE
update GNOME runtime to 3.38

### ISSUE THREAD

**Issue by eszlari** [flathub/work.openpaper.Paperwork#5]

**Comment by jflesch** [comment]
I did try but it's so easy. My last attempt at updating to Gnome runtime 3.38 caused major issues. It seems it causes problems with python-pillow, which in turn prevent the GUI from starting.

I'm going to try again later.

**Comment by eszlari** [comment]
> It seems it causes problems with python-pillow, which in turn prevent the GUI from starting.

Have you tried updating pillow? In the new runtime Python got updated from 3.7 to 3.8, there might be a incompatibility with the old pillow version.

**Comment by jmaibaum** [comment]
Any news on this? The GNOME 3.36 runtime is now EOL, and users of this package get this warning on `flatpak update`:

```console
$ flatpak update
Looking for updates…
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   work.openpaper.Paperwork
Nothing to do.
```

**Comment by jflesch** [comment]
OK, it seems to work fine with Gnome runtime 40: 71c7147f62432bea731089529d3fa1612e3d8603
